language: node_js
node_js:
- '8'
services:
- mongodb
script:
- npm run lint
- npm run build
- npm test
notifications:
  slack:
    rooms:
      secure: UEaeWdN3yYZJA2oe37iVhpFgKy0XWLhOIPpsU09k/olARvP1y2oH5SpSBiySf0GpqfyEmiiqtVdGQ36A9HxIfO+AnFAYk5FObdLnm0iremWQE0KsLPgE3LUYDX2VzI+Z7Bt4K9umsloKwtBtS4oOpm0mo+NcKn/5R8WrgZKLFwSEx0k/s3JtOW21W59vT/96J30tX8AJmCE9txC/MjIHLpVUPKV4HMhpjMu+OkCeW//oC3guSRocq0du63OyIig+TiE0hojR7sxkzSgONGtaDkGxcW+BIdXzAfR1eUKKAr1UB7XHAag+ShW+hiVlthRas89M29U9RG8QHGAo2abDZLRC3GIRmdAH9bTrlk0RpdhUMN50yQO5YSy3h2JOlbcIBYPfxgqggMtTzU0JgeTbDZVrNKwUFpat6LPehlwiHRmOriQNYVf1eiv4MxHxtoKYfIs3iNAfjedcOg9aIA1bTWVJOUqsGEeZ8uJmvlhmZo2wjW8jCvxCrSs83x4OgkvBiQP1ME3Aoqdj6z0gtGJEMEAMUo5LJu+RmPWU2w4OE02HNK7aowdO8icb+6sIUS2ZdbGvhaMFdDEInL+yD57qSOcL2nTNX4myO5P4sshdchbBmJZ8TI/vNLdRpT99zjGo6+MWiLNGcmzQCXwK2rbKAHWB38UUB+dwClZH99ZuJkI=
