name: test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      FIBERY_TOKEN: ${{ secrets.FIBERY_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: use node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: start mongodb
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2

      - name: update submodules
        run: git submodule update --init

      - name: install
        run: |
          npm ci

      - name: test
        run: npm test
